import Navbar from "@/components/home/navbar";
import Footer from "@/components/footer/footer";
import "./globals.css";

export const metadata = {
  title: "News",
  description: "Generated by Regodev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="eng">
      <body className="bg-[#eef2f6]">
        <div className="fixed w-full">
          <Navbar />
        </div>
        <div className="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
